metadata:
  name: che-idea-ultimate
components:
  - type: cheEditor
    reference: 'https://raw.githubusercontent.com/che-incubator/jetbrains-editor-images/meta/che-idea/latest.meta.yaml'
    alias: che-idea-ultimate
apiVersion: 1.0.0
